### ISSUE TITLE
Prototype machine learning frameworks for network communications

### ISSUE THREAD

**Issue by kevfoerster** [awesome-inc/docker-selks#4]
Test multiple machine learning frameworks. Ideas right now:

- brain.js
- H2O

In the future, we want to use them for low-code environments, so look for "easy-to-click" environments.

**Comment by mkoertgen** [comment]
My 2 cents:

- https://github.com/josephmisiti/awesome-machine-learning
- https://github.com/jivoi/awesome-ml-for-cybersecurity
